
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Bill extends javax.swing.JFrame {
    String username;
    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
        curDateTime();
    }
    public Bill(String usernamme) {
        this.username=usernamme;
        initComponents();
        tf.setText(username);
    }
    
    public void curDateTime(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd  HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        datetime.setText(dtf.format(now));
    }
    
    /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cusname = new javax.swing.JLabel();
        datetime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(785, 520));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century", 0, 26)); // NOI18N
        jLabel2.setText("BILL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, 40));

        jButton1.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jButton1.setText("PAY BILL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 150, 40));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 610, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 610, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/small_Icon.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 100, 80));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Items", "Quantity", "Price"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 640, 190));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 80, 20));

        cusname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cusname.setForeground(new java.awt.Color(0, 0, 102));
        cusname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(cusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 140, 20));

        datetime.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        datetime.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(datetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 160, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("  TOTAL  AMOUNT   =");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 130, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 80, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("        QUATITY         = ");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 130, 20));

        jLabel9.setFont(new java.awt.Font("Goudy Old Style", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("VEGGIES FOR YOU");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 220, 40));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xtra_small-icon.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 90, 40));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xtra_small-icon.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 90, 40));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xtra_small-icon.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 90, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xtra_small-icon.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 90, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 660, 300));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 480));
        jPanel1.add(tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 160, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         //TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/veggies","root","MySQL");
            
            Statement st=con.createStatement();
            
            st.executeUpdate("UPDATE zz"+username+" set zAmount=zAmount+(SELECT Amount FROM "+username+" where Items='Apples'), zQuantity=zQuantity+(SELECT Quantity FROM "+username+" where Items='Apples') where zItems='Apples'");
            st.executeUpdate("UPDATE zz"+username+" set zAmount=zAmount+(SELECT Amount FROM "+username+" where Items='Oranges'), zQuantity=zQuantity+(SELECT Quantity FROM "+username+" where Items='Oranges') where zItems='Oranges'");
            st.executeUpdate("UPDATE zz"+username+" set zAmount=zAmount+(SELECT Amount FROM "+username+" where Items='Kiwi'), zQuantity=zQuantity+(SELECT Quantity FROM "+username+" where Items='Kiwi') where zItems='Kiwi'");
            st.executeUpdate("UPDATE zz"+username+" set zAmount=zAmount+(SELECT Amount FROM "+username+" where Items='Banana'), zQuantity=zQuantity+(SELECT Quantity FROM "+username+" where Items='Banana') where zItems='Banana'");
            st.executeUpdate("UPDATE zz"+username+" set zAmount=zAmount+(SELECT Amount FROM "+username+" where Items='Grapes'), zQuantity=zQuantity+(SELECT Quantity FROM "+username+" where Items='Grapes') where zItems='Grapes'");
            st.executeUpdate("UPDATE zz"+username+" set zAmount=zAmount+(SELECT Amount FROM "+username+" where Items='Pineapple'), zQuantity=zQuantity+(SELECT Quantity FROM "+username+" where Items='Pineapple') where zItems='Pineapple'");
            st.executeUpdate("UPDATE zz"+username+" set zAmount=zAmount+(SELECT Amount FROM "+username+" where Items='Spinach'), zQuantity=zQuantity+(SELECT Quantity FROM "+username+" where Items='Spinach') where zItems='Spinach'");
            st.executeUpdate("UPDATE zz"+username+" set zAmount=zAmount+(SELECT Amount FROM "+username+" where Items='Tomato'), zQuantity=zQuantity+(SELECT Quantity FROM "+username+" where Items='Tomato') where zItems='Tomato'");
            st.executeUpdate("UPDATE zz"+username+" set zAmount=zAmount+(SELECT Amount FROM "+username+" where Items='Cabbage'), zQuantity=zQuantity+(SELECT Quantity FROM "+username+" where Items='Cabbage') where zItems='Cabbage'");
            st.executeUpdate("UPDATE zz"+username+" set zAmount=zAmount+(SELECT Amount FROM "+username+" where Items='Beans'), zQuantity=zQuantity+(SELECT Quantity FROM "+username+" where Items='Beans') where zItems='Beans'");
            st.executeUpdate("UPDATE zz"+username+" set zAmount=zAmount+(SELECT Amount FROM "+username+" where Items='Lady Finger'), zQuantity=zQuantity+(SELECT Quantity FROM "+username+" where Items='Lady Finger') where zItems='Lady Finger'");
            st.executeUpdate("UPDATE zz"+username+" set zAmount=zAmount+(SELECT Amount FROM "+username+" where Items='Raddish'), zQuantity=zQuantity+(SELECT Quantity FROM "+username+" where Items='Raddish') where zItems='Raddish'");
            
            st.executeUpdate("UPDATE stock set Quantity=Quantity-(SELECT Quantity FROM "+username+" where Items='Apples') where Items='Apples'");
            st.executeUpdate("UPDATE stock set Quantity=Quantity-(SELECT Quantity FROM "+username+" where Items='Oranges') where Items='Oranges'");
            st.executeUpdate("UPDATE stock set Quantity=Quantity-(SELECT Quantity FROM "+username+" where Items='Kiwi') where Items='Kiwi'");
            st.executeUpdate("UPDATE stock set Quantity=Quantity-(SELECT Quantity FROM "+username+" where Items='Banana') where Items='Banana'");
            st.executeUpdate("UPDATE stock set Quantity=Quantity-(SELECT Quantity FROM "+username+" where Items='Grapes') where Items='Grapes'");
            st.executeUpdate("UPDATE stock set Quantity=Quantity-(SELECT Quantity FROM "+username+" where Items='Pineapple') where Items='Pineapple'");
            st.executeUpdate("UPDATE stock set Quantity=Quantity-(SELECT Quantity FROM "+username+" where Items='Spinach') where Items='Spinach'");
            st.executeUpdate("UPDATE stock set Quantity=Quantity-(SELECT Quantity FROM "+username+" where Items='Tomato') where Items='Tomato'");
            st.executeUpdate("UPDATE stock set Quantity=Quantity-(SELECT Quantity FROM "+username+" where Items='Cabbage') where Items='Cabbage'");
            st.executeUpdate("UPDATE stock set Quantity=Quantity-(SELECT Quantity FROM "+username+" where Items='Beans') where Items='Beans'");
            st.executeUpdate("UPDATE stock set Quantity=Quantity-(SELECT Quantity FROM "+username+" where Items='Lady Finger') where Items='Lady Finger'");
            st.executeUpdate("UPDATE stock set Quantity=Quantity-(SELECT Quantity FROM "+username+" where Items='Raddish') where Items='Raddish'");
            
            PreparedStatement pst = con.prepareStatement("DROP TABLE "+username+";");
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"You have successfully payed!!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        Thankyou c=new Thankyou();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cusname.setText(username);
        curDateTime();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/veggies","root","MySQL");
            PreparedStatement pst = con.prepareStatement("SELECT * FROM "+username+" WHERE Quantity>0;");
            ResultSet rs=pst.executeQuery();
            
            while(rs.next()){
                String items=rs.getString("Items");
                String quantity=rs.getString("Quantity");
                String amount=rs.getString("Amount");
                
                String tbData[]= {items, quantity, amount};
                DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                tb1Model.addRow(tbData);
            }
            
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        int numrow = jTable1.getRowCount();
        double tot = 0;
        for (int i = 0; i < numrow; i++) {
            double val = Double.valueOf(jTable1.getValueAt(i, 2).toString());
            tot += val ;
        }
        jLabel7.setText(Double.toString(tot));
        
        int Numrow = jTable1.getRowCount();
        double Tot = 0;
        for (int i = 0; i < Numrow; i++) {
            double val = Double.valueOf(jTable1.getValueAt(i, 1).toString());
            Tot += val ;
        }
        jLabel1.setText(Double.toString(Tot));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cusname;
    private javax.swing.JLabel datetime;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf;
    // End of variables declaration//GEN-END:variables
}
